/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class co_lobi_sdk_jni_CustomNativeActivity */

#ifndef _Included_co_lobi_sdk_jni_CustomNativeActivity
#define _Included_co_lobi_sdk_jni_CustomNativeActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     co_lobi_sdk_jni_CustomNativeActivity
 * Method:    onResult
 * Signature: (ILjava/lang/String;JJ)V
 */
JNIEXPORT void JNICALL Java_co_lobi_sdk_jni_CustomNativeActivity_onResult
  (JNIEnv *, jobject, jint, jstring, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
